version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=squarehelha
      - POSTGRES_PASSWORD=squarepass
      - POSTGRES_DB=squaredb
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"

volumes:
  data: